modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/erudites-dev/image-viewer/issues"

[[mods]]
modId="imageviewer"
displayName="Image Viewer"
version="${version}"
authors="shihyeon"
description='''
Renders server-provided images in an in-game browser overlay.
'''
displayURL="https://modrinth.com/mod/image-viewer"

[[mixins]]
config="imageviewer.mixins.json"

[[dependencies.imageviewer]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.imageviewer]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.imageviewer]]
modId="mcef"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"